# Generated by Django 6.0.2 on 2026-02-05 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_book_production_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='production_year',
            new_name='publication_year',
        ),
    ]
